### ISSUE TITLE
Compatibility Issue with GLIBC Version in Server Environment

### ISSUE THREAD

**Issue by YangSJ2019** [dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching#2]
Hello @dongliangcao ,

I hope this message finds you well. First of all, I would like to express my appreciation for your work and the valuable contribution you have made to the community.

I have been trying to run your code on a server environment, but unfortunately, I encountered a compatibility issue with the GLIBC version. The server's GLIBC version is lower than the minimum requirement specified in your code. As you may know, upgrading the GLIBC version on the server is not a straightforward task and may have significant implications for other applications running on it.

I wanted to reach out to you to inquire if there are any alternative solutions or workarounds to address this compatibility issue without necessarily upgrading the GLIBC version. I understand that GLIBC is a critical dependency for your code, but I wondered if there might be any configuration options or modifications that could enable successful execution on systems with lower GLIBC versions.

I believe that finding a workaround for this compatibility issue would greatly benefit users who face similar constraints on their server environments. Your insights and suggestions would be highly appreciated.

Thank you for your time and consideration. I look forward to hearing from you and continuing to contribute to the development of your project.

**Comment by dongliangcao** [comment]
Hi,

Thanks a lot for your interest about this work. Could you specify which library causes the dependency issue of the GLIBC?

Best,
Dongliang

**Comment by YangSJ2019** [comment]
Hi,

Thanks for your reply! I screenshot the error reported below，it says GLIBC is required by open3d.
![image](https://github.com/dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching/assets/92658865/6c827c11-7dcb-4697-a302-c039949ac39f)

**Comment by dongliangcao** [comment]
Hi,

There are two solutions that you can try:
1) Install a version of Open3D that is compatible with your GLIBC version.
2) In the repository, Open3D is used only for read/write triangle meshes, you can easily find other libraries to replace it.
