### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by llm-96** [dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching#3]
Hi, thanks for the great work. I am running inference given your provided checkpoints. In Table 3, the result for (train-test) Faust-Faust, Scape-Scape matches with what you have reported. However, the cross dataset F-S, S-F is quite bad. F-S gains 6.66  (2.2 reported), and S-F gains 4.58 (1.6 reported). I leave my config file for F-S below. It would be great if you can take a look to see if there is a problem. Thank you.

```html
# general setting
name: faust_on_scape
backend: dp # DataParallel
type: FMNetModel
num_gpu: auto
manual_seed: 1234
non-isometric: false
partial: false
visualize: true

# path
path:
  resume_state: checkpoints/faust.pth
  resume: false

# datasets
datasets:
  test_dataset:
    name: ScapeVal
    type: PairScapeDataset
    phase: test
    data_root: ../data/SCAPE_r/
    return_evecs: true
    return_faces: true
    num_evecs: 200
    return_corr: true
    return_dist: true

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 256
    cache_dir: ../data/SCAPE_r/diffusion
    input_type: wks
  permutation:
    type: Similarity
    tau: 0.07
    hard: true

# validation setting
val:
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

```

**Comment by dongliangcao** [comment]
Sorry for the later reply. I think the main reason is that for cross-dataset test, we use our test-time optimisation strategy as described in the paper. Please check the config files that use test-time optimisation for testing, e.g. [DT4D-H interclass](https://github.com/dongliangcao/Unsupervised-Learning-of-Robust-Spectral-Shape-Matching/blob/main/options/test/dt4d_interclass.yaml).
